server:
    port: 8082
    shutdown: graceful
spring:
    application:
        name: simulator
    kafka:
        bootstrap-servers: http://localhost:9092
management:
    endpoints:
        web:
            exposure:
                include: '*'
    tracing:
        enabled: false
        sampling:
            probability: 0.0
    metrics:
        distribution:
            percentiles-histogram:
                http:
                    server:
                        requests: true
        tags:
            application: ${spring.application.name}

