server:
    port: 8082
    shutdown: graceful
spring:
    application:
        name: simulator
    kafka:
        bootstrap-servers: http://localhost:9092
    data:
        redis:
            host: localhost
            port: 6380      # Redis port for microservices instance
            password: redis-pass
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
management:
    endpoints:
        web:
            exposure:
                include: '*'
    tracing:
        enabled: false
        sampling:
            probability: 0.0
    metrics:
        distribution:
            percentiles-histogram:
                http:
                    server:
                        requests: true
        tags:
            application: ${spring.application.name}

