server:
  port: 8083
  shutdown: graceful
spring:
  application:
    name: rules
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: false
    sampling:
      probability: 0.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}

