server:
  port: 8083
  shutdown: graceful
grpc:
  server:
    port: 8090
spring:
  application:
    name: rules
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: false
    sampling:
      probability: 0.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  info:
    git:
      mode: full

