server:
  port: 8083
  shutdown: graceful
grpc:
  client:
    rules-service:
      address: 'static://localhost:8090'
      negotiationType: plaintext
      enable-keep-alive: true
      keepAliveWithoutCalls: true
spring:
  application:
    name: rules
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgresql://localhost:5432/drools?currentSchema=ru}"
    username: "${DB_USERNAME:ruleuser}"
    password: "${DB_PASSWORD:ruleuser}"
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      username: default
#      password: redis-pass
#      database: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: false
    sampling:
      probability: 0.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  info:
    git:
      mode: full

