-- ORDERS SERVICE
CREATE SCHEMA IF NOT EXISTS wo;
CREATE USER wouser WITH PASSWORD 'wouser';
GRANT USAGE ON SCHEMA wo TO wouser;
GRANT CREATE ON SCHEMA wo TO wouser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA wo TO wouser;
ALTER DEFAULT PRIVILEGES IN SCHEMA wo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wouser;

-- RULES SERVICE
CREATE  SCHEMA IF NOT EXISTS ru;
CREATE USER ruleuser WITH PASSWORD 'ruleuser';
GRANT USAGE ON SCHEMA ru TO ruleuser;
GRANT CREATE ON SCHEMA ru TO ruleuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ru TO ruleuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA ru GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ruleuser;

