insert into wo.job (code,creation_date,"name",active_status) values
('YY171T',NOW(),'Equity Investment Instruments','N'),
('ZY074P',NOW(),'Electricity','Y'),
('CI069K',NOW(),'General Industry','Y'),
('VB733A',NOW(),'Leisure Goods','Y'),
('VX528U',NOW(),'Nonequity Investment Instruments','Y'),
('MH453G',NOW(),'Tobacco','Y'),
('UL915E',NOW(),'Industrial Metals & Mining','Y'),
('SB741U',NOW(),'Forestry & Paper','Y'),
('XL844Q',NOW(),'Alternative Energy','Y'),
('PP088M',NOW(),'Oil & Gas Producers','N'),
('PA757Z',NOW(),'Oil & Gas Sellers','Y'),
('YR808G',NOW(),'Technology Hardware & Equipment','N'),
('EY945M',NOW(),'Mining','N'),
('TH504U',NOW(),'Oil & Gas Producers','Y'),
('WV831J',NOW(),'Fixed Line Telecommunications','Y'),
('TI843W',NOW(),'General Industrials','Y'),
('MQ208B',NOW(),'Banks','Y'),
('SM466I',NOW(),'Pharmaceuticals & Biotechnology','Y'),
('FY987O',NOW(),'Automobiles & Parts','Y'),
('LW192Z',NOW(),'Electricity New','Y'),
('RK286U',NOW(),'Real Estate Investment Trusts','Y'),
('AI743N',NOW(),'Oil Equipment, Services & Distribution','N'),
('FJ884M',NOW(),'Gas, Water & Multiutilities','Y'),
('MK160K',NOW(),'Food & Drug Retailers','Y'),
('FK113Z',NOW(),'Mobile Telecommunications','Y');