server:
  port: 8081
  shutdown: graceful
grpc:
  server:
    port: 8090
spring:
  application:
    name: work_order
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgresql://localhost:5432/drools?currentSchema=wo}"
    username: "${DB_USERNAME:wouser}"
    password: "${DB_PASSWORD:wouser}"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: wo-group-2
      key-deserializer: org.apache.messaging.common.serialization.StringDeserializer
      value-deserializer: org.apache.messaging.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: false
    sampling:
      probability: 0.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  info:
    git:
      mode: full

