server:
  port: 8081
  shutdown: graceful
grpc:
  client:
    rules-service:
      address: 'static://localhost:8090'
      negotiationType: plaintext
      enable-keep-alive: true
      keepAliveWithoutCalls: true
spring:
  application:
    name: work_order
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgresql://localhost:5432/drools?currentSchema=wo}"
    username: "${DB_USERNAME:drools}"
    password: "${DB_PASSWORD:drools}"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: wo-group-2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    enable:
      idempotence: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: false
    sampling:
      probability: 0.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  info:
    git:
      mode: full

