package org.acme.rules.drools;

unit WoDataUnit;

import java.util.List
import java.util.Set
import java.util.stream.Collectors
import org.acme.rules.drools.WoData;
import org.acme.rules.drools.WoJob;


rule "disable job for jobtype"
dialect "java"
when
     $order: /orders[ getJobTypeCode() == "code1" ]
     $job: /orders[ $order.containsJobCode("job1") ]
then
     System.out.println($order.getWoNumber() + " - applied rule: disable job1 for code1");
     $order.disableJob("job1","disable job for jobtype");
end

