name: Work Order Service
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build With Maven
        run: mvn --batch-mode --update-snapshots verify

