name: Work Order Service
run-name: ${{ github.actor }}
on:
  push:
    paths:
      - work-order/**
    branches:
      - '**'
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./work-order
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/micro1-work-order
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Build With Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Build Docker Image
        if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
        run: |
          echo "Building the Docker image..."
          docker build -no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/micro1-work-order .
      - if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
        name: Build and Publish Docker Image
        run: |
          mvn spring-boot:build-image -DskipTests -DskipProtoc
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME
